# Configure the database used when in the development environment
development:
  adapter: postgresql
  encoding: unicode
  database: movies
  pool: 5
  username: nf1213
  password: pw

# Configure the database used when in the test environment
test:
  adapter: postgresql
  encoding: unicode
  database: movies
  pool: 5
  username: nf1213
  password: pw

# Configure the database used when in the production environment
production:
  adapter: postgresql
  encoding: unicode
  database: movies
  pool: 5
  username: nf1213
  password: pw
